apiVersion: workload.codeflare.dev/v1beta1
kind: AppWrapper
metadata:
  name: appwrapper-sample
spec:
  priority: 5
  schedulingSpec:
    minAvailable: 1
    requeuing:
      timeInSeconds: 5
      maxNumRequeuings: 0
  resources:
    GenericItems:
    - custompodresources:
      - replicas: 1
        requests: {}
      generictemplate:
        apiVersion: v1
        kind: Pod
        metadata:
          namespace: default
          name: test-1
          labels:
            appwrapper.mcad.ibm.com/namespace: default
            appwrapper.mcad.ibm.com: test
        spec:
          restartPolicy: Never
          containers:
          - name: busybox
            image: busybox
            command: ["sh", "-c", "sleep 3"]
